INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (1, 'Air Bomb', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (2, 'Air Defence', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (3, 'Archer Tower', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (4, 'Army Camp', 2);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (5, 'Barracks', 2);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (6, 'Bomb', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (7, 'Cannon', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (8, 'Clan Castle', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (9, 'Dark Barracks', 2);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (10, 'Dark Elixir Storage', 2);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (11, 'Elixir Collector', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (12, 'Elixir Storage', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (13, 'Giant Bomb', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (14, 'Gold Mine', 2);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (15, 'Gold Storage', 2);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (16, 'Hidden Tesla', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (17, 'Laboratory', 2);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (18, 'Mortar', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (19, 'Seeking Air Mine', 1);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (20, 'Spell Factory', 2);
INSERT INTO tblElement (ElementID, ElementName, CostType) VALUES (21, 'Wizard Tower', 1);
