package com.derekgillett.clashercalendar.test;

import android.database.sqlite.SQLiteDatabase;
import android.util.Log;

import com.derekgillett.clashercalendar.ClasherDBContract;
import com.derekgillett.clashercalendar.Element;
import com.derekgillett.clashercalendar.MySQLiteHelper;
import com.derekgillett.clashercalendar.Player;
import com.derekgillett.clashercalendar.PlayerElement;

import junit.framework.TestCase;

public class PlayerTest extends TestCase {
	private static final String TAG = "PlayerTest";
	private SQLiteDatabase moDB;
	
	public PlayerTest(String name) {
		super(name);
	}

	protected void setUp() throws Exception {
		super.setUp();
		MySQLiteHelper mySQLiteHelper = MySQLiteHelper.getInstance();
		moDB = mySQLiteHelper.getWritableDatabase();
	}

	protected void tearDown() throws Exception {
		super.tearDown();
		moDB = null;
	}

	public void testCreatePlayerTH1() {
		String[][] elements = {
				{"Army Camp", "0", "" },
				{"Barracks", "0", "" },
				{"Canon", "0", "" },
				{"Canon", "0", "" },
				{"Elixir Collector", "0", "" },
				{"Elixir Storage", "0", "" },
				{"Gold Mine", "0", "" },
				{"Gold Storage", "0", "" },
				{ClasherDBContract.TOWNHALL_NAME, "1", "" }
		};
		
		CreatePlayer(1, "Dezgoville TH1", elements);
	}
	
	public void testCreatePlayerTH2() {
		String[][] elements = {
				{"Gold Mine", "2", "" },
				{"Gold Mine", "0", "" },
				{"Elixir Collector", "2", "" },
				{"Elixir Collector", "0", "" },
				{"Elixir Storage", "1", "" },
				{"Gold Storage", "1", "" },
				{"Barracks", "3", "" },
				{"Barracks", "0", "" },
				{"Army Camp", "1", "" },

				{"Canon", "2", "" },
				{"Canon", "2", "" },
				{"Archer Tower", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{ClasherDBContract.TOWNHALL_NAME, "2", "" },
		};

		CreatePlayer(2, "Dezgoville TH2", elements);
	}
	
	public void testCreatePlayerTH3() {
		String[][] elements = {
				{"Archer Tower", "2", "" },
				{"Army Camp", "2", "" },
				{"Army Camp", "0", "" },
				{"Barracks", "4", "" },
				{"Barracks", "4", "" },
				{"Bomb", "0", "" },
				{"Bomb", "0", "" },
				{"Canon", "3", "" },
				{"Canon", "3", "" },
				{"Elixir Collector", "0", "" },
				{"Elixir Collector", "4", "" },
				{"Elixir Collector", "4", "" },
				{"Elixir Storage", "0", "" },
				{"Elixir Storage", "3", "" },
				{"Gold Mine", "4", "" },
				{"Gold Mine", "4", "" },
				{"Gold Mine", "0", "" },
				{"Gold Storage", "0", "" },
				{"Gold Storage", "3", "" },
				{"Laboratory", "0", "" },
				{"Mortar", "0", "" },
				{ClasherDBContract.TOWNHALL_NAME, "3", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "2", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" }
		};

		CreatePlayer(3, "Dezgoville TH3", elements);
	}

	public void testCreatePlayerTH4() {
		String[][] elements = {
				{"Air Defence", "0", ""},
				{"Archer Tower", "3", ""},
				{"Archer Tower", "0", ""},
				{"Army Camp", "3", ""},
				{"Army Camp", "3", ""},
				{"Barracks", "5", ""},
				{"Barracks", "5", ""},
				{"Barracks", "0", ""},
				{"Bomb", "2", ""},
				{"Bomb", "2", ""},
				{"Canon", "4", ""},
				{"Canon", "4", ""},
				{"Elixir Collector", "6", ""},
				{"Elixir Collector", "6", ""},
				{"Elixir Collector", "6", ""},
				{"Elixir Collector", "0", ""},
				{"Elixir Storage", "6", ""},
				{"Elixir Storage", "6", ""},
				{"Gold Mine", "6", ""},
				{"Gold Mine", "6", ""},
				{"Gold Mine", "6", ""},
				{"Gold Mine", "0", ""},
				{"Gold Storage", "6", ""},
				{"Gold Storage", "6", ""},
				{"Laboratory", "1", ""},
				{"Mortar", "1", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{ClasherDBContract.TOWNHALL_NAME, "4", ""},
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },
				{"Wall", "3", "" },

				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
		};

		CreatePlayer(4, "Dezgoville TH4", elements);
	}

	public void testCreatePlayerTH5() {
		String[][] elements = {
				{"Air Bomb", "0", ""} ,
				{"Air Bomb", "0", ""} ,
				{"Air Defence", "2", ""} ,
				{"Archer Tower", "0", ""} ,
				{"Archer Tower", "4", ""} ,
				{"Archer Tower", "4", ""} ,
				{"Army Camp", "0", ""} ,
				{"Army Camp", "4", ""} ,
				{"Army Camp", "4", ""} ,
				{"Barracks", "6", ""} ,
				{"Barracks", "6", ""} ,
				{"Barracks", "6", ""} ,
				{"Bomb", "0", ""} ,
				{"Bomb", "0", ""} ,
				{"Bomb", "2", ""} ,
				{"Bomb", "2", ""} ,
				{"Canon", "0", ""} ,
				{"Canon", "5", ""} ,
				{"Canon", "5", ""} ,
				{"Elixir Collector", "0", ""} ,
				{"Elixir Collector", "8", ""} ,
				{"Elixir Collector", "8", ""} ,
				{"Elixir Collector", "8", ""} ,
				{"Elixir Collector", "8", ""} ,
				{"Elixir Storage", "8", ""} ,
				{"Elixir Storage", "8", ""} ,
				{"Gold Mine", "0", ""} ,
				{"Gold Mine", "8", ""} ,
				{"Gold Mine", "8", ""} ,
				{"Gold Mine", "8", ""} ,
				{"Gold Mine", "8", ""} ,
				{"Gold Storage", "8", ""} ,
				{"Gold Storage", "8", ""} ,
				{"Laboratory", "2", ""} ,
				{"Mortar", "2", ""} ,
				{"Spell Factory", "0", ""} ,
				{"Spring Trap", "0", ""} ,
				{"Spring Trap", "0", ""} ,
				{ClasherDBContract.TOWNHALL_NAME, "5", ""} ,
				{"Wizard Tower", "0", ""} ,

				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				{"Wall", "4", "" },
				
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
			};

		CreatePlayer(5, "Dezgoville TH5", elements);
	}

	public void testCreatePlayerTH6() {
		String[][] elements = {
				{"Air Bomb", "2", ""},
				{"Air Bomb", "2", ""},
				{"Air Defence", "3", ""},
				{"Archer Tower", "6", ""},
				{"Archer Tower", "6", ""},
				{"Archer Tower", "6", ""},
				{"Army Camp", "5", ""},
				{"Army Camp", "5", ""},
				{"Army Camp", "5", ""},
				{"Barracks", "7", ""},
				{"Barracks", "7", ""},
				{"Barracks", "7", ""},
				{"Bomb", "3", ""},
				{"Bomb", "3", ""},
				{"Bomb", "3", ""},
				{"Bomb", "3", ""},
				{"Canon", "6", ""},
				{"Canon", "6", ""},
				{"Canon", "6", ""},
				{"Elixir Collector", "0", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Storage", "9", ""},
				{"Elixir Storage", "9", ""},
				{"Giant Bomb", "0", ""},
				{"Gold Mine", "0", ""},
				{"Gold Mine", "10", ""},
				{"Gold Mine", "10", ""},
				{"Gold Mine", "10", ""},
				{"Gold Mine", "10", ""},
				{"Gold Mine", "10", ""},
				{"Gold Storage", "9", ""},
				{"Gold Storage", "9", ""},
				{"Laboratory", "3", ""},

				{"Mortar", "3", ""},
				{"Spell Factory", "1", ""},
				{"Wizard Tower", "2", ""},

				{"Mortar", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{ClasherDBContract.TOWNHALL_NAME, "6", ""},
				{"Wizard Tower", "0", ""},

				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				{"Wall", "5", "" },
				
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
			};

		CreatePlayer(6, "Dezgoville TH6", elements);
	}

	public void testCreatePlayerTH7() {
		String[][] elements = {
				{"Air Bomb", "2", ""},
				{"Air Bomb", "2", ""},
				{"Air Defence", "4", ""},
				{"Air Defence", "0", ""},
				{"Archer Tower", "0", ""},
				{"Archer Tower", "7", ""},
				{"Archer Tower", "7", ""},
				{"Archer Tower", "7", ""},
				{"Army Camp", "0", ""},
				{"Army Camp", "6", ""},
				{"Army Camp", "6", ""},
				{"Army Camp", "6", ""},
				{"Barbarian King Alter", "0", ""},
				{"Barracks", "8", ""},
				{"Barracks", "8", ""},
				{"Barracks", "8", ""},
				{"Barracks", "0", ""},
				{"Bomb", "0", ""},
				{"Bomb", "0", ""},
				{"Bomb", "3", ""},
				{"Bomb", "3", ""},
				{"Bomb", "3", ""},
				{"Bomb", "3", ""},
				{"Canon", "0", ""},
				{"Canon", "0", ""},
				{"Canon", "7", ""},
				{"Canon", "7", ""},
				{"Canon", "7", ""},
				{"Dark Barracks", "0", ""},
				{"Dark Elixir Storage", "0", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Collector", "10", ""},
				{"Elixir Storage", "10", ""},
				{"Elixir Storage", "10", ""},
				{"Giant Bomb", "0", ""},
				{"Giant Bomb", "2", ""},
				{"Gold Mine", "10", ""},
				{"Gold Mine", "10", ""},
				{"Gold Mine", "10", ""},
				{"Gold Mine", "10", ""},
				{"Gold Mine", "10", ""},
				{"Gold Mine", "10", ""},
				{"Gold Storage", "10", ""},
				{"Gold Storage", "10", ""},
				{"Hidden Tesla", "0", ""},
				{"Hidden Tesla", "0", ""},
				{"Laboratory", "4", ""},
				{"Mortar", "4", ""},
				{"Mortar", "4", ""},
				{"Mortar", "0", ""},
				{"Seeking Air Mine", "0", ""},
				{"Spell Factory", "2", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{ClasherDBContract.TOWNHALL_NAME, "7", ""},
				{"Wizard Tower", "3", ""},
				{"Wizard Tower", "3", ""},

				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
				{"Wall", "6", "" },
								
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
		};

		CreatePlayer(7, "Dezgoville TH7", elements);
	}

	public void testCreatePlayerTH8() {
		String[][] elements = {
				{"Air Bomb", "3", ""},
				{"Air Bomb", "3", ""},
				{"Air Bomb", "0", ""},
				{"Air Bomb", "0", ""},
				{"Air Defence", "5", ""},
				{"Air Defence", "5", ""},
				{"Air Defence", "0", ""},
				{"Archer Tower", "8", ""},
				{"Archer Tower", "8", ""},
				{"Archer Tower", "8", ""},
				{"Archer Tower", "8", ""},
				{"Archer Tower", "0", ""},
				{"Army Camp", "6", ""},
				{"Army Camp", "6", ""},
				{"Army Camp", "6", ""},
				{"Army Camp", "6", ""},
				{"Barbarian King Alter", "1", ""},
				{"Barracks", "9", ""},
				{"Barracks", "9", ""},
				{"Barracks", "9", ""},
				{"Barracks", "9", ""},
				{"Bomb", "4", ""},
				{"Bomb", "4", ""},
				{"Bomb", "4", ""},
				{"Bomb", "4", ""},
				{"Bomb", "4", ""},
				{"Bomb", "4", ""},
				{"Canon", "8", ""},
				{"Canon", "8", ""},
				{"Canon", "8", ""},
				{"Canon", "8", ""},
				{"Canon", "8", ""},
				{"Dark Barracks", "2", ""},
				{"Dark Barracks", "0", ""},
				{"Dark Elixir Drill", "0", ""},
				{"Dark Elixir Storage", "2", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Storage", "11", ""},
				{"Elixir Storage", "11", ""},
				{"Elixir Storage", "0", ""},
				{"Giant Bomb", "2", ""},
				{"Giant Bomb", "2", ""},
				{"Giant Bomb", "0", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Storage", "11", ""},
				{"Gold Storage", "11", ""},
				{"Gold Storage", "0", ""},
				{"Hidden Tesla", "0", ""},
				{"Hidden Tesla", "3", ""},
				{"Hidden Tesla", "3", ""},
				{"Laboratory", "5", ""},
				{"Mortar", "5", ""},
				{"Mortar", "5", ""},
				{"Mortar", "5", ""},
				{"Seeking Air Mine", "1", ""},
				{"Seeking Air Mine", "0", ""},
				{"Spell Factory", "3", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{ClasherDBContract.TOWNHALL_NAME, "8", ""},
				{"Wizard Tower", "4", ""},
				{"Wizard Tower", "4", ""},
				{"Wizard Tower", "0", ""},
				
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				{"Wall", "7", "" },
				
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
		};
		
		CreatePlayer(8, "Dezgoville TH8", elements);
	}

	public void testCreatePlayerTH9() {
		String[][] elements = {
				{"Air Bomb", "3", ""},
				{"Air Bomb", "3", ""},
				{"Air Bomb", "3", ""},
				{"Air Bomb", "3", ""},
				{"Air Defence", "6", ""},
				{"Air Defence", "6", ""},
				{"Air Defence", "6", ""},
				{"Air Defence", "0", ""},
				{"Archer Queen Alter", "0", ""},
				{"Archer Tower", "10", ""},
				{"Archer Tower", "10", ""},
				{"Archer Tower", "10", ""},
				{"Archer Tower", "10", ""},
				{"Archer Tower", "10", ""},
				{"Archer Tower", "0", ""},
				{"Army Camp", "6", ""},
				{"Army Camp", "6", ""},
				{"Army Camp", "6", ""},
				{"Army Camp", "6", ""},
				{"Barbarian King Alter", "1", ""},
				{"Barracks", "10", ""},
				{"Barracks", "10", ""},
				{"Barracks", "10", ""},
				{"Barracks", "10", ""},
				{"Bomb", "5", ""},
				{"Bomb", "5", ""},
				{"Bomb", "5", ""},
				{"Bomb", "5", ""},
				{"Bomb", "5", ""},
				{"Bomb", "5", ""},
				{"Canon", "10", ""},
				{"Canon", "10", ""},
				{"Canon", "10", ""},
				{"Canon", "10", ""},
				{"Canon", "10", ""},
				{"Dark Barracks", "4", ""},
				{"Dark Barracks", "4", ""},
				{"Dark Elixir Drill", "3", ""},
				{"Dark Elixir Drill", "0", ""},
				{"Dark Elixir Storage", "4", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Storage", "11", ""},
				{"Elixir Storage", "11", ""},
				{"Elixir Storage", "11", ""},
				{"Elixir Storage", "0", ""},
				{"Giant Bomb", "3", ""},
				{"Giant Bomb", "3", ""},
				{"Giant Bomb", "3", ""},
				{"Giant Bomb", "0", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Storage", "11", ""},
				{"Gold Storage", "11", ""},
				{"Gold Storage", "11", ""},
				{"Gold Storage", "0", ""},
				{"Hidden Tesla", "6", ""},
				{"Hidden Tesla", "6", ""},
				{"Hidden Tesla", "6", ""},
				{"Hidden Tesla", "0", ""},
				{"Laboratory", "6", ""},
				{"Mortar", "6", ""},
				{"Mortar", "6", ""},
				{"Mortar", "6", ""},
				{"Seeking Air Mine", "1", ""},
				{"Seeking Air Mine", "1", ""},
				{"Seeking Air Mine", "0", ""},
				{"Seeking Air Mine", "0", ""},
				{"Spell Factory", "3", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{ClasherDBContract.TOWNHALL_NAME, "9", ""},
				{"Wizard Tower", "6", ""},
				{"Wizard Tower", "6", ""},
				{"Wizard Tower", "6", ""},
				{"Wizard Tower", "0", ""},
				{"X-Bow", "0", ""},
				{"X-Bow", "0", ""},
				
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				{"Wall", "8", "" },
				
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
				{"Wall", "0", "" },
		};	

		CreatePlayer(9, "Dezgoville TH9", elements);
	}

	public void testCreatePlayerTH10() {
		String[][] elements = {
				{"Air Bomb", "4", ""},
				{"Air Bomb", "4", ""},
				{"Air Bomb", "4", ""},
				{"Air Bomb", "4", ""},
				{"Air Bomb", "0", ""},
				{"Air Defence", "7", ""},
				{"Air Defence", "7", ""},
				{"Air Defence", "7", ""},
				{"Air Defence", "7", ""},
				{"Archer Queen Alter", "1", ""},
				{"Archer Tower", "11", ""},
				{"Archer Tower", "11", ""},
				{"Archer Tower", "11", ""},
				{"Archer Tower", "11", ""},
				{"Archer Tower", "11", ""},
				{"Archer Tower", "11", ""},
				{"Archer Tower", "0", ""},
				{"Army Camp", "7", ""},
				{"Army Camp", "7", ""},
				{"Army Camp", "7", ""},
				{"Army Camp", "7", ""},
				{"Barbarian King Alter", "1", ""},
				{"Barracks", "10", ""},
				{"Barracks", "10", ""},
				{"Barracks", "10", ""},
				{"Barracks", "10", ""},
				{"Bomb", "6", ""},
				{"Bomb", "6", ""},
				{"Bomb", "6", ""},
				{"Bomb", "6", ""},
				{"Bomb", "6", ""},
				{"Bomb", "6", ""},
				{"Canon", "11", ""},
				{"Canon", "11", ""},
				{"Canon", "11", ""},
				{"Canon", "11", ""},
				{"Canon", "11", ""},
				{"Canon", "0", ""},
				{"Dark Barracks", "6", ""},
				{"Dark Barracks", "6", ""},
				{"Dark Elixir Drill", "6", ""},
				{"Dark Elixir Drill", "6", ""},
				{"Dark Elixir Drill", "0", ""},
				{"Dark Elixir Storage", "6", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "11", ""},
				{"Elixir Collector", "0", ""},
				{"Elixir Storage", "11", ""},
				{"Elixir Storage", "11", ""},
				{"Elixir Storage", "11", ""},
				{"Elixir Storage", "11", ""},
				{"Giant Bomb", "3", ""},
				{"Giant Bomb", "3", ""},
				{"Giant Bomb", "3", ""},
				{"Giant Bomb", "3", ""},
				{"Giant Bomb", "0", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "11", ""},
				{"Gold Mine", "0", ""},
				{"Gold Storage", "11", ""},
				{"Gold Storage", "11", ""},
				{"Gold Storage", "11", ""},
				{"Gold Storage", "11", ""},
				{"Hidden Tesla", "7", ""},
				{"Hidden Tesla", "7", ""},
				{"Hidden Tesla", "7", ""},
				{"Hidden Tesla", "7", ""},
				{"Inferno Tower", "0", ""},
				{"Inferno Tower", "0", ""},
				{"Laboratory", "7", ""},
				{"Mortar", "7", ""},
				{"Mortar", "7", ""},
				{"Mortar", "7", ""},
				{"Seeking Air Mine", "2", ""},
				{"Seeking Air Mine", "2", ""},
				{"Seeking Air Mine", "2", ""},
				{"Seeking Air Mine", "2", ""},
				{"Seeking Air Mine", "0", ""},
				{"Spell Factory", "4", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{"Spring Trap", "0", ""},
				{ClasherDBContract.TOWNHALL_NAME, "10", ""},
				{"Wizard Tower", "7", ""},
				{"Wizard Tower", "7", ""},
				{"Wizard Tower", "7", ""},
				{"Wizard Tower", "7", ""},
				{"X-Bow", "3", ""},
				{"X-Bow", "3", ""},
				{"X-Bow", "0", ""},


				
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
				{"Wall", "10", "" },
		};

		CreatePlayer(10, "Dezgoville TH10", elements);
	}

	private boolean findElement(PlayerElement poPlayerElement, String[][] poElements) {
		boolean bFound = false;
		int nPos = 0;
		while(!bFound && nPos < poElements.length) {
			// 
			if (poPlayerElement.getElement().getName().equals(poElements[nPos][0]) && 
				poPlayerElement.getLevel() == Integer.parseInt(poElements[nPos][1]) && 
				poElements[nPos][2].equals("")) {
				poElements[nPos][2] = "found";
				bFound = true;
			}
			nPos++;
		}
		return bFound;
	}
	
	private void CreatePlayer(int pnTHLevel, String psVillageName, String[][] poElements) {//, int[] poElementQtys) {

		//assertTrue("Test setup issue - elementQtys size <> elements size", poElementQtys.length == poElements.length);

		int numElements_Expected = poElements.length;
		int numElements_Actual = 0;
		
		Player oPlayer = new Player(moDB, pnTHLevel, psVillageName);
		Log.v("PlayerTest.testCreatePlayer", "Start Create Plater TH Level " + pnTHLevel);
		oPlayer.showPlayerElements();
		oPlayer.moveToFirst();
		while (!oPlayer.isAfterLast()) {
			PlayerElement oPlayerElement = oPlayer.getPlayerElement();
			Element oElement = oPlayerElement.getElement();
			
			String sMsg = "Looking for " + oElement.getName() + " lvl " + oPlayerElement.getLevel();
			Log.v(TAG, sMsg);
				
			assertTrue(sMsg,findElement(oPlayerElement, poElements));

			numElements_Actual++;
			oPlayer.moveToNext();
		}
		
		assertTrue("Found " + numElements_Actual + ", expecting " + numElements_Expected,numElements_Expected == numElements_Actual);
		
		oPlayer.delete();
		Log.v("PlayerTest.testCreatePlayer", "Finish");
	}
	
}